### ISSUE TITLE
Meaning of superfluous mixed cells and associated terms

### ISSUE THREAD

**Issue by timduff35** [janverschelde/PHCpack#30]
[phcIn.txt](https://github.com/janverschelde/PHCpack/files/5576810/phcIn.txt)

On the attached input file, I run phc -m, with the MixedVol algorithm, w/ stable mixed volume included. The output includes the following:

==> Volume : 2 superfluous.
common mixed volume : 16
stable mixed volume : 16
 total mixed volume : 18

Are the terms "superfluous" and "common", and "total" defined somewhere? I didn't succeed in finding them in documentation.

**Comment by janverschelde** [comment]
The documentation indeed does not describe superfluous mixed cells,
but these are cells with inner normals that have at least one negative coordinate.
Those superfluous cells have the artificial origin, but do not contribute to the stable mixed volume,
because of the occurrence of negative coordinates in their inner normals.

**Comment by timduff35** [comment]
That clears things things up, thanks!
