### ISSUE TITLE
GNAT runtime dependency

### ISSUE THREAD

**Issue by hsidky** [janverschelde/PHCpack#6]
Hello, 

I am trying to deploy PHCPy on a cluster and I am having difficulty doing so due to dependency on the GNAT runtime library. I successfully compiled and tested phcpy.so and my python code on my local machine. However, the production systems I need to run on do not have the runtime libraries nor do I have the capability of installing them.

I took a peek at the Makefile, and it looks like the C dependencies are statically linked but some Ada ones are not. I have no knowledge of Ada, but I tried linking against the static library without any success. 

Since the PHCPack binary is distributed and runs without issue on my production machines, I was wondering if you had any insight as to doing the same with the shared object.

Thanks.

**Comment by janverschelde** [comment]
Hi Hythem,

thanks for raising this issue.  The problem is in the final
linking stage that builds a shared object file (.so),
where it could/should have been an archive (one .a file).

I will try to fix this issue, but currently I am traveling
and testing my solution might be a bit difficult as
all my computers do have the GNAT runtime library.

Best regards,
       Jan

**Comment by janverschelde** [comment]
This issue is resolved in release 2.4.33 of PHCpack.  The shared object needed for phcpy can be compiled to include the archive with statically linked Ada code.  The instructions are in the makefile_unix, in the Objects directory of the source code.  Then the shared object is no longer dependent on GNAT and it can be transferred to computers that do not have the gnu-ada compiler installed.

**Comment by hsidky** [comment]
Thanks!
